// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frballqenqmzdrfonoky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyYmFsbHFlbnFtemRyZm9ub2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMTQ4NDYsImV4cCI6MjA1Nzc5MDg0Nn0.LovGBBlAdIZKUSs5MiXyR6ZoxM9WkGuZSWcv79P2luY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);